# Generated by Django 5.0.14 on 2025-10-09 20:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("families", "0001_initial"),
        ("trips", "0002_resort_check_in_time_resort_check_out_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroceryListTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "is_system_template",
                    models.BooleanField(
                        default=False, help_text="System templates cannot be deleted"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_grocery_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        blank=True,
                        help_text="Family that owns this template (null for system templates)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_templates",
                        to="families.family",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GroceryListTemplateItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., Produce, Dairy, Meat, Snacks, Beverages",
                        max_length=100,
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                (
                    "quantity",
                    models.CharField(
                        blank=True,
                        help_text="e.g., '2 lbs', '1 gallon', '6 pack'",
                        max_length=100,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="For custom sorting within category"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="grocery.grocerylisttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="TripGroceryList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'Week 1 Groceries', 'Pre-Trip Shopping'",
                        max_length=200,
                    ),
                ),
                ("shopping_date", models.DateField(blank=True, null=True)),
                ("store_name", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Family member assigned to this shopping trip",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_grocery_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "based_on_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this list was created from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_lists",
                        to="grocery.grocerylisttemplate",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grocery_lists",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["shopping_date", "name"],
            },
        ),
        migrations.CreateModel(
            name="TripGroceryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("item_name", models.CharField(max_length=200)),
                ("quantity", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("is_purchased", models.BooleanField(default=False)),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="For custom sorting within category"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grocery_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="grocery.tripgrocerylist",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "order", "item_name"],
            },
        ),
        migrations.AddIndex(
            model_name="grocerylisttemplate",
            index=models.Index(
                fields=["family", "is_system_template"],
                name="grocery_gro_family__e35c3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="grocerylisttemplateitem",
            index=models.Index(
                fields=["template", "category"], name="grocery_gro_templat_ebb5d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripgrocerylist",
            index=models.Index(fields=["trip"], name="grocery_tri_trip_id_ffaf38_idx"),
        ),
        migrations.AddIndex(
            model_name="tripgrocerylist",
            index=models.Index(
                fields=["assigned_to"], name="grocery_tri_assigne_934810_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tripgroceryitem",
            index=models.Index(
                fields=["grocery_list", "category"],
                name="grocery_tri_grocery_66baa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tripgroceryitem",
            index=models.Index(
                fields=["grocery_list", "is_purchased"],
                name="grocery_tri_grocery_fa7c9b_idx",
            ),
        ),
    ]
