# Generated by Django 5.0.14 on 2025-10-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resort",
            name="check_in_time",
            field=models.TimeField(
                blank=True,
                help_text="Typical check-in time (e.g., 3:00 PM)",
                null=True,
                verbose_name="check-in time",
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="check_out_time",
            field=models.TimeField(
                blank=True,
                help_text="Typical check-out time (e.g., 11:00 AM)",
                null=True,
                verbose_name="check-out time",
            ),
        ),
        migrations.AddField(
            model_name="resort",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="phone number"
            ),
        ),
    ]
