# Generated by Django 5.0.14 on 2025-10-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_resort_check_in_time_resort_check_out_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("dream", "Dream Trip"),
                    ("planning", "Planning"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                ],
                default="planning",
                max_length=10,
                verbose_name="status",
            ),
        ),
    ]
