# Generated by Django 5.0.14 on 2025-10-08 01:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="family name")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "family",
                "verbose_name_plural": "families",
                "db_table": "families",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                (
                    "token",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="invitation token",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="families.family",
                        verbose_name="family",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="invited by",
                    ),
                ),
            ],
            options={
                "verbose_name": "family invitation",
                "verbose_name_plural": "family invitations",
                "db_table": "family_invitations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["family", "status"],
                        name="family_invi_family__47aa39_idx",
                    ),
                    models.Index(
                        fields=["email", "status"], name="family_invi_email_ccc0d0_idx"
                    ),
                    models.Index(fields=["token"], name="family_invi_token_766ec0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("member", "Member"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="role",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="joined at"),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="families.family",
                        verbose_name="family",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "family member",
                "verbose_name_plural": "family members",
                "db_table": "family_members",
                "ordering": ["-joined_at"],
                "indexes": [
                    models.Index(
                        fields=["family", "role"], name="family_memb_family__949b93_idx"
                    )
                ],
                "unique_together": {("family", "user")},
            },
        ),
    ]
