# Generated by Django 5.0.14 on 2025-10-08 02:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0002_resort_check_in_time_resort_check_out_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PackingListTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="template name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_system_template",
                    models.BooleanField(
                        default=False,
                        help_text="Built-in template that cannot be deleted",
                        verbose_name="system template",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_packing_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "packing list template",
                "verbose_name_plural": "packing list templates",
                "db_table": "packing_list_templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TripPackingList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., 'David's List', 'Kids' List', 'Beach Gear'",
                        max_length=200,
                        verbose_name="list name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person responsible for this list",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_packing_lists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="assigned to",
                    ),
                ),
                (
                    "based_on_template",
                    models.ForeignKey(
                        blank=True,
                        help_text="Template this list was created from (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trip_lists",
                        to="packing.packinglisttemplate",
                        verbose_name="based on template",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="packing_lists",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip packing list",
                "verbose_name_plural": "trip packing lists",
                "db_table": "trip_packing_lists",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TripPackingItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., Clothing, Electronics, Toiletries",
                        max_length=100,
                        verbose_name="category",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=200, verbose_name="item name"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                (
                    "is_packed",
                    models.BooleanField(default=False, verbose_name="packed"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "packing_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="packing.trippackinglist",
                        verbose_name="packing list",
                    ),
                ),
            ],
            options={
                "verbose_name": "packing item",
                "verbose_name_plural": "packing items",
                "db_table": "trip_packing_items",
                "ordering": ["category", "order", "item_name"],
            },
        ),
        migrations.CreateModel(
            name="PackingListTemplateItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        help_text="e.g., Clothing, Electronics, Toiletries",
                        max_length=100,
                        verbose_name="category",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=200, verbose_name="item name"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="quantity",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="packing.packinglisttemplate",
                        verbose_name="template",
                    ),
                ),
            ],
            options={
                "verbose_name": "template item",
                "verbose_name_plural": "template items",
                "db_table": "packing_list_template_items",
                "ordering": ["category", "order", "item_name"],
                "indexes": [
                    models.Index(
                        fields=["template", "category"],
                        name="packing_lis_templat_13fd1a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="trippackinglist",
            index=models.Index(fields=["trip"], name="trip_packin_trip_id_845992_idx"),
        ),
        migrations.AddIndex(
            model_name="trippackinglist",
            index=models.Index(
                fields=["assigned_to"], name="trip_packin_assigne_d1f56c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trippackingitem",
            index=models.Index(
                fields=["packing_list", "category"],
                name="trip_packin_packing_580dbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trippackingitem",
            index=models.Index(
                fields=["packing_list", "is_packed"],
                name="trip_packin_packing_4d251b_idx",
            ),
        ),
    ]
