# Generated by Django 5.0.14 on 2025-10-09 21:02

import django.db.models.deletion
from django.db import migrations, models


def consolidate_packing_lists(apps, schema_editor):
    """
    Consolidate multiple packing lists per trip into one.
    Keep the first list for each trip and merge all items from other lists into it.
    """
    TripPackingList = apps.get_model("packing", "TripPackingList")
    TripPackingItem = apps.get_model("packing", "TripPackingItem")

    # Get all trips that have multiple packing lists
    from django.db.models import Count
    trips_with_multiple_lists = (
        TripPackingList.objects.values("trip_id")
        .annotate(list_count=Count("id"))
        .filter(list_count__gt=1)
    )

    for trip_data in trips_with_multiple_lists:
        trip_id = trip_data["trip_id"]

        # Get all lists for this trip, ordered by creation date
        lists = TripPackingList.objects.filter(trip_id=trip_id).order_by("created_at")

        # Keep the first list, merge others into it
        primary_list = lists.first()
        duplicate_lists = lists[1:]

        # Move all items from duplicate lists to the primary list
        for dup_list in duplicate_lists:
            # Update all items to point to the primary list
            TripPackingItem.objects.filter(packing_list=dup_list).update(
                packing_list=primary_list
            )

            # Delete the duplicate list
            dup_list.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("packing", "0002_seed_default_templates"),
        ("trips", "0002_resort_check_in_time_resort_check_out_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trippackinglist",
            options={
                "ordering": ["created_at"],
                "verbose_name": "trip packing list",
                "verbose_name_plural": "trip packing lists",
            },
        ),
        # Consolidate multiple lists before changing the schema
        migrations.RunPython(consolidate_packing_lists, migrations.RunPython.noop),
        migrations.RemoveIndex(
            model_name="trippackinglist",
            name="trip_packin_trip_id_845992_idx",
        ),
        migrations.RemoveIndex(
            model_name="trippackinglist",
            name="trip_packin_assigne_d1f56c_idx",
        ),
        migrations.RemoveField(
            model_name="trippackinglist",
            name="assigned_to",
        ),
        migrations.RemoveField(
            model_name="trippackinglist",
            name="name",
        ),
        migrations.AlterField(
            model_name="trippackinglist",
            name="trip",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packing_list",
                to="trips.trip",
                verbose_name="trip",
            ),
        ),
    ]
