# Generated by Django 5.0.14 on 2025-10-08 02:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0002_activity_travel_time_from_resort_and_more"),
        ("itinerary", "0001_initial"),
        ("trips", "0002_resort_check_in_time_resort_check_out_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyJournal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Which day of the trip?", verbose_name="date"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="What happened today? How was the experience?",
                        verbose_name="journal entry",
                    ),
                ),
                (
                    "weather",
                    models.CharField(
                        blank=True,
                        help_text='Optional: Weather conditions (e.g., "Sunny, 78°F")',
                        max_length=100,
                        verbose_name="weather",
                    ),
                ),
                (
                    "mood_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "😞 Poor"),
                            (2, "😐 Fair"),
                            (3, "🙂 Good"),
                            (4, "😊 Great"),
                            (5, "🤩 Excellent"),
                        ],
                        help_text="How was your overall mood today?",
                        null=True,
                        verbose_name="mood rating",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="journal_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal_entries",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily journal",
                "verbose_name_plural": "daily journals",
                "db_table": "daily_journals",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["trip", "-date"], name="daily_journ_trip_id_0c2018_idx"
                    ),
                    models.Index(
                        fields=["trip", "created_by"],
                        name="daily_journ_trip_id_c4a1e3_idx",
                    ),
                ],
                "unique_together": {("trip", "date", "created_by")},
            },
        ),
        migrations.CreateModel(
            name="TripPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="trip_photos/%Y/%m/%d/", verbose_name="photo"
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the photo",
                        verbose_name="caption",
                    ),
                ),
                (
                    "taken_date",
                    models.DateField(
                        blank=True,
                        help_text="When was this photo taken?",
                        null=True,
                        verbose_name="date taken",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="uploaded at"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link this photo to a specific activity",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="activities.activity",
                        verbose_name="activity",
                    ),
                ),
                (
                    "daily_itinerary",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional: Link this photo to a specific day/event",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="itinerary.dailyitinerary",
                        verbose_name="itinerary item",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_photos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "trip photo",
                "verbose_name_plural": "trip photos",
                "db_table": "trip_photos",
                "ordering": ["-taken_date", "-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["trip", "-taken_date"],
                        name="trip_photos_trip_id_a3a6cd_idx",
                    ),
                    models.Index(
                        fields=["trip", "-uploaded_at"],
                        name="trip_photos_trip_id_2f0397_idx",
                    ),
                    models.Index(
                        fields=["activity"], name="trip_photos_activit_aa3df7_idx"
                    ),
                    models.Index(
                        fields=["daily_itinerary"],
                        name="trip_photos_daily_i_4514b5_idx",
                    ),
                ],
            },
        ),
    ]
