# Generated by Django 5.0.14 on 2025-10-08 02:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0002_activity_travel_time_from_resort_and_more"),
        ("trips", "0002_resort_check_in_time_resort_check_out_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyItinerary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Day of the trip", verbose_name="date"),
                ),
                (
                    "time_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start time (optional)",
                        null=True,
                        verbose_name="start time",
                    ),
                ),
                (
                    "time_end",
                    models.TimeField(
                        blank=True,
                        help_text="End time (optional)",
                        null=True,
                        verbose_name="end time",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text='For standalone events like "Breakfast" or "Check-in"',
                        max_length=200,
                        verbose_name="title",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or details",
                        verbose_name="notes",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order for items on the same day",
                        verbose_name="order",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to an activity (optional for standalone events)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itinerary_items",
                        to="activities.activity",
                        verbose_name="activity",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_itinerary_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary_items",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "daily itinerary item",
                "verbose_name_plural": "daily itinerary items",
                "db_table": "daily_itinerary",
                "ordering": ["date", "time_start", "order"],
                "indexes": [
                    models.Index(
                        fields=["trip", "date"], name="daily_itine_trip_id_49529d_idx"
                    ),
                    models.Index(
                        fields=["trip", "date", "order"],
                        name="daily_itine_trip_id_2882ca_idx",
                    ),
                    models.Index(
                        fields=["activity"], name="daily_itine_activit_e44e20_idx"
                    ),
                ],
            },
        ),
    ]
