# Generated by Django 5.0.14 on 2025-10-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="travel_time_from_resort",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Estimated driving time from resort (auto-calculated from distance)",
                null=True,
                verbose_name="travel time from resort (minutes)",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="distance_from_resort",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance from resort in miles (auto-calculated if address provided)",
                max_digits=6,
                null=True,
                verbose_name="distance from resort (miles)",
            ),
        ),
    ]
