# Generated by Django 5.0.14 on 2025-10-08 03:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trips", "0002_resort_check_in_time_resort_check_out_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g., Lodging, Food, Activities, Transportation",
                        max_length=100,
                        verbose_name="category name",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        choices=[
                            ("#2E86AB", "Ocean Blue"),
                            ("#FF6B6B", "Sunset Coral"),
                            ("#06A77D", "Palm Green"),
                            ("#F4E8C1", "Sandy Beige"),
                            ("#9B59B6", "Purple"),
                            ("#E67E22", "Orange"),
                            ("#3498DB", "Sky Blue"),
                            ("#E74C3C", "Red"),
                        ],
                        default="#2E86AB",
                        help_text="Hex color for UI organization",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first",
                        verbose_name="display order",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_categories",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "budget category",
                "verbose_name_plural": "budget categories",
                "db_table": "budget_categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Brief description of the expense",
                        max_length=200,
                        verbose_name="description",
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Estimated cost in USD",
                        max_digits=10,
                        verbose_name="estimated amount",
                    ),
                ),
                (
                    "actual_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Actual cost in USD (leave blank until paid)",
                        max_digits=10,
                        null=True,
                        verbose_name="actual amount",
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when payment was made",
                        null=True,
                        verbose_name="payment date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this expense",
                        verbose_name="notes",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="budget.budgetcategory",
                        verbose_name="category",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budget_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="budget_items_paid",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="paid by",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget_items",
                        to="trips.trip",
                        verbose_name="trip",
                    ),
                ),
            ],
            options={
                "verbose_name": "budget item",
                "verbose_name_plural": "budget items",
                "db_table": "budget_items",
                "ordering": ["category__order", "category__name", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="budgetcategory",
            index=models.Index(
                fields=["trip", "order"], name="budget_cate_trip_id_6a1403_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetcategory",
            constraint=models.UniqueConstraint(
                fields=("trip", "name"), name="unique_budget_category_per_trip"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitem",
            index=models.Index(
                fields=["trip", "category"], name="budget_item_trip_id_3eef04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitem",
            index=models.Index(
                fields=["trip", "paid_by"], name="budget_item_trip_id_bf6be8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budgetitem",
            index=models.Index(
                fields=["payment_date"], name="budget_item_payment_3584ac_idx"
            ),
        ),
    ]
